### KROK 1: Rejestracja użytkownika
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "student8",
  "email": "student@example.com",
  "password": "BezpieczneHaslo123"
}

### KROK 2: Logowanie
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "student8",
  "password": "BezpieczneHaslo123"
}

### KROK 3: Test dostępu (Wklej ACCESS TOKEN)
GET http://localhost:8080/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdHVkZW50OCIsImlhdCI6MTc2OTU0NzcyNiwiZXhwIjoxNzY5NjM0MTI2fQ.mfAqEEsf4GD8f2g4E_70S1QwF42z90WFWewqHu4eLl0

### KROK 4: Dodaj zadanie (Wklej ACCESS TOKEN)
POST http://localhost:8080/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdHVkZW50OCIsImlhdCI6MTc2OTU0NzcyNiwiZXhwIjoxNzY5NjM0MTI2fQ.mfAqEEsf4GD8f2g4E_70S1QwF42z90WFWewqHu4eLl0

{
  "title": "Zrobić projekt na studia",
  "description": "Dokończyć Lab 13 - Refresh Token",
  "completed": true
}

### KROK 5: Pobierz zadania (Wklej ACCESS TOKEN)
GET http://localhost:8080/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdHVkZW50OCIsImlhdCI6MTc2OTU0NzcyNiwiZXhwIjoxNzY5NjM0MTI2fQ.mfAqEEsf4GD8f2g4E_70S1QwF42z90WFWewqHu4eLl0

### KROK 6: ODŚWIEŻANIE TOKENA (Wklej REFRESH TOKEN)
POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "3b6c5eb5-7918-4467-a566-6a95534dcc7d"
}